spring:
  # Настройки базы данных для разработки
  datasource:
    url: jdbc:postgresql://localhost:5432/fiba_dev
    username: postgres
    password: postgres
  
  # Настройки JPA для разработки
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Настройки почты для разработки
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: true

# Настройки логирования для разработки
logging:
  level:
    root: DEBUG
    com.fiba.api: TRACE
  file:
    name: logs/application-dev.log

# Настройки CORS для разработки
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080,http://localhost:4200 